#!/usr/bin/env python3

import os
import sys
import requests
import json

def main():
    APP_URL = os.environ.get('APP_URL')
    if APP_URL is None:
        print("Variável de ambiente APP_URL não encontrada. Tente rodar o env_var novamente.")
    elif (len(sys.argv) < 2):
        print("Nenhum argumento encontrado. Utilize tarefa '-h' para mais informações de uso.")
    else:
        option = sys.argv[1]

        # options = ["adicionar", "listar", "buscar", "apagar", "atualizar"]
        if (sys.argv[1] == "adicionar"):
            try:
                task_name = sys.argv[2]
                payload = {"nome" : task_name}
                r = requests.post(APP_URL + "Tarefa", data=json.dumps(payload))
                try:
                    print(r.json())
                except:
                    print("Ocorreu um erro ao tentar adicionar uma nova tarefa.")
            except:
                print("Comando inválido. Utilize tarefa '-h' para mais informações de uso.")
        elif (sys.argv[1] == "listar"):
            r = requests.get(APP_URL + "Tarefa")
            try:
                print(r.json())
            except:
                print("Ocorreu um erro ao tentar listar as tarefas.")
        elif (sys.argv[1] == "buscar"):
            try:
                r = requests.get(APP_URL + "Tarefa/" + sys.argv[2])
                try:
                    print(r.json())
                except:
                    print("Ocorreu um erro ao tentar buscar uma tarefa.")
            except:
                print("Comando inválido. Utilize tarefa '-h' para mais informações de uso.")
        elif (sys.argv[1] == "apagar"):
            try:
                r = requests.delete(APP_URL + "Tarefa/" + sys.argv[2])
                if (r.status_code == 200):
                    print("Tarefa deletada com sucesso.")
                else:
                    print("Ocorreu um erro ao tentar deletar a tarefa.")
            except:
                print("Comando inválido. Utilize tarefa '-h' para mais informações de uso.")
        elif (sys.argv[1] == "atualizar"):
            try:
                task_id = sys.argv[2]
                task_name = sys.argv[3]
                payload = {"nome" : task_name}
                r = requests.put(APP_URL + "Tarefa/" + task_id, data=json.dumps(payload))
                if (r.status_code == 200):
                    print("Tarefa atualizada com sucesso.")
                else:
                    print("Ocorreu um erro ao tentar atualizar a tarefa.")
            except:
                print("Comando inválido. Utilize tarefa '-h' para mais informações de uso.")

        elif (sys.argv[1] == "-h"):
            print("Comandos disponíveis: adicionar, listar, buscar, apagar, atualizar.")
            print("tarefa adicionar <task.name> -- Adicionar uma nova tarefa")
            print("tarefa listar -- Lista todas as tarefas")
            print("tarefa buscar <task.id> -- Busca uma tarefa específica dada um id")
            print("tarefa apagar <task.id> -- Apaga uma tarefa específica dada um id")
            print("tarefa atualizar <task.id> <task.name> -- Atualiza as informações de uma tarefa existente")
        else:
            print("Comando não encontrado. Utilize tarefa '-h' para mais informações de uso.")

if __name__ == '__main__':
    main()